name: run-tests
run-name: ${{ github.actor }} requested tests
on:
  pull_request:
    types:
      - opened
    branches:
      - "main"
    paths:
      - "**/*.js"
      - "**/*.ts"
  push:
    branches:
      - "main"
    paths:
      - "**/*.js"
      - "**/*.ts"

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Bun
        uses: oven-sh/setup-bun@v2

      - name: Run tests
        run: bun test
